#!/usr/bin/env bash
# This Script connects to the server 54.157.176.41 using the users private key
# stored in a file school Found in the users home directory

ssh -i ~/.ssh/id_rsa ubuntu@100.26.133.213
